name = "UI Passport"
license = "MIT"
licenselink = ""
description = "Passport User Interface"
homepage = "https://z17.dev"
tags = ["website", "responsive", "multilingual", "mobile"]
features = ["posts", "shortcodes", "comments"]
min_version = "0.88.0"

[author]
  name = "z17 Dev"
  homepage = "https://z17.dev"
